AWSTemplateFormatVersion: "2010-09-09"

Description:
  "an aerosol consisting of a visible mass of miniature liquid droplets, frozen crystals, or other particles suspended in the atmosphere of a planetary body or similar space."

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: better-than-bad-its-wood
      RetentionInDays: 1