AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: an aerosol consisting of a visible mass of miniature liquid droplets, frozen crystals, or other particles suspended in the atmosphere of a planetary body or similar space.

Parameters:
  DefaultBucketOnCreateObjectFunctionArn:
    Default: ''
    Type: String
    # AllowedPattern: '^(arn:aws:lambda:us-east-1:458362456643:function:abr-DefaultBucketOnCreateObjectFunction)?$'
    AllowedValues:
      - ''
      - arn:aws:lambda:us-east-1:458362456643:function:abr-DefaultBucketOnCreateObjectFunction
  
  DefaultBucketOnCreateObjectFunctionVersion:
    Type: String
    AllowedPattern: '^v\d\.\d\.\d'

Conditions:
  DefaultBucketOnCreateObjectFunctionDoesNotExist: !Equals [!Ref 'DefaultBucketOnCreateObjectFunctionArn', '']

Resources:
  DefaultBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${AWS::StackName}-default"
      AccessControl: BucketOwnerFullControl
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 2
            Status: Enabled
      NotificationConfiguration: !If
        - DefaultBucketOnCreateObjectFunctionDoesNotExist
        - !Ref 'AWS::NoValue'
        - LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: image
            Function: !Sub "${DefaultBucketOnCreateObjectFunctionArn}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE

  DefaultBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DefaultBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub
              - "arn:${AWS::Partition}:s3:::${Bucket}/*"
              - Bucket: !Ref "DefaultBucket"
            Principal:
              CanonicalUser: !GetAtt DefaultBucketCloudFrontOriginAccessIdentity.S3CanonicalUserId

  DefaultBucketCloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: DefaultBucketCloudFrontOriginAccessIdentity

  LambdaFunctionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${AWS::StackName}-lambda-functions"
      AccessControl: BucketOwnerFullControl
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 2
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE

  PrimaryDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: !Ref DefaultBucket
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6" # CachingOptimized: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html
          ViewerProtocolPolicy: redirect-to-https
        Origins:
          - Id: !Ref DefaultBucket
            DomainName: !Sub
              - "${Bucket}.s3.${AWS::Region}.${AWS::URLSuffix}"
              - Bucket: !Ref DefaultBucket
            S3OriginConfig:
              OriginAccessIdentity: !Sub
                - "origin-access-identity/cloudfront/${Identity}"
                - Identity: !Ref DefaultBucketCloudFrontOriginAccessIdentity

  DefaultBucketOnCreateObjectFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt DefaultBucketOnCreateObjectFunction.Arn
      Principal: s3.amazonaws.com
      SourceArn: !Sub
        - "arn:${AWS::Partition}:s3:::${Bucket}"
        - Bucket: !Ref "DefaultBucket"
      SourceAccount: !Ref AWS::AccountId

  DefaultBucketOnCreateObjectFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: LogGroupAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*"
        - PolicyName: LogStreamAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-DefaultBucketOnCreateObjectFunction:*"

  DefaultBucketOnCreateObjectFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-DefaultBucketOnCreateObjectFunction"
      Code:
        S3Bucket: !Ref LambdaFunctionBucket
        # S3Key: !Sub "default-bucket-on-create-object/${Version}/index.js.zip"
        S3Key: !Sub
          - "default-bucket-on-create-object/${Version}/index.js.zip"
          - Version: !Ref DefaultBucketOnCreateObjectFunctionVersion
      Handler: index.handler
      PackageType: Zip
      Role: !GetAtt DefaultBucketOnCreateObjectFunctionRole.Arn
      Runtime: nodejs14.x
      # Runtime: nodejs16.x